# Generated by Django 2.1.4 on 2018-12-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allstars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('coach_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('won', models.IntegerField(blank=True, null=True)),
                ('lost', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'coach',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('draft_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('draft_round', models.IntegerField()),
                ('draft_selection', models.IntegerField()),
                ('draft_overall', models.IntegerField()),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('name_suffix', models.CharField(blank=True, max_length=5, null=True)),
                ('draft_from', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'draft',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonRecord',
            fields=[
                ('person_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('person_id_long', models.CharField(max_length=10, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30)),
                ('full_given_name', models.CharField(blank=True, max_length=100, null=True)),
                ('name_suffix', models.CharField(blank=True, max_length=5, null=True)),
                ('nickname', models.CharField(blank=True, max_length=30, null=True)),
                ('pos', models.CharField(blank=True, max_length=10, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('college', models.CharField(blank=True, max_length=50, null=True)),
                ('birthdate', models.CharField(blank=True, max_length=20, null=True)),
                ('birth_city', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_state', models.CharField(blank=True, max_length=20, null=True)),
                ('birth_country', models.CharField(blank=True, max_length=50, null=True)),
                ('high_school', models.CharField(blank=True, max_length=50, null=True)),
                ('hs_city', models.CharField(blank=True, max_length=50, null=True)),
                ('hs_state', models.CharField(blank=True, max_length=20, null=True)),
                ('hs_country', models.CharField(blank=True, max_length=30, null=True)),
                ('death_date', models.CharField(blank=True, max_length=20, null=True)),
                ('race', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'person_record',
                'managed': False,
            },
        ),
    ]
