# Generated by Django 2.1.4 on 2018-12-15 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allstars', '0002_coach_draft_personrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamAlign',
            fields=[
                ('team_align_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('stint', models.IntegerField(blank=True, null=True)),
                ('games_played', models.IntegerField(blank=True, null=True)),
                ('minutes', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('assists', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'team_align',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='allstar',
            options={'managed': False, 'ordering': ['player_record__last_name'], 'verbose_name': 'Basketball All Star Records', 'verbose_name_plural': 'Basketball All Star Records'},
        ),
    ]
