# Generated by Django 2.1.4 on 2018-12-15 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allstars', '0003_auto_20181214_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'managed': False, 'ordering': ['person_record__last_name', 'person_record__first_name'], 'verbose_name': "Men's Professional Basketball Coach/Team Alignment", 'verbose_name_plural': "Men's Professional Basketball Coach/Team Alignment"},
        ),
        migrations.AlterModelOptions(
            name='league',
            options={'managed': False, 'ordering': ['league_name'], 'verbose_name': "Men's Professional Basketball League", 'verbose_name_plural': "Men's Professional Basketball Leagues"},
        ),
        migrations.AlterModelOptions(
            name='personrecord',
            options={'managed': False, 'ordering': ['last_name', 'first_name'], 'verbose_name': "Men's Professional Basketball Player/Coach", 'verbose_name_plural': "Men's Professional Basketball Players/Coaches"},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'managed': False, 'ordering': ['name'], 'verbose_name': "Men's Professional Basketball Team", 'verbose_name_plural': "Men's Professional Basketball Teams"},
        ),
        migrations.AlterModelOptions(
            name='teamalign',
            options={'managed': False, 'ordering': ['team__name'], 'verbose_name': "Men's Professional Basketball Player/Team Alignment", 'verbose_name_plural': "Men's Professional Basketball Player/Team Alignment"},
        ),
        migrations.AlterModelOptions(
            name='teamstat',
            options={'managed': False, 'ordering': ['year', 'team__name'], 'verbose_name': "Men's Professional Basketball Team Stats", 'verbose_name_plural': "Men's Professional Basketball Team Stats"},
        ),
    ]
