# Generated by Django 2.1.4 on 2018-12-15 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allstars', '0004_auto_20181214_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allstar',
            options={'managed': False, 'ordering': ['person_record__last_name'], 'verbose_name': 'Basketball All Star Records', 'verbose_name_plural': 'Basketball All Star Records'},
        ),
    ]
