# Generated by Django 2.1.4 on 2018-12-17 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allstars', '0005_auto_20181214_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allstar',
            options={'managed': False, 'ordering': ['person_record__last_name', 'person_record__first_name', 'league__league_name'], 'verbose_name': 'Basketball All Star Records', 'verbose_name_plural': 'Basketball All Star Records'},
        ),
    ]
